'use strict';
// Noms affichés des produits d'une commande (extraits des pages de commande). « rizprod » est volontairement absent :
// le riz est notifié à part (semaine en cours), pas dans les modifications de commande.
module.exports = {
  "bo": "Bun Bò",
  "sin": "Singapour",
  "thai": "Thaï",
  "thon": "Thon mariné",
  "plp": "Poulpe",
  "rouleaux": "Rouleaux printemps",
  "pokethon": "Poke thon",
  "pokesaumon": "Poke saumon",
  "tataki": "Tataki",
  "tiramisu": "Tiramisu",
  "ananas": "Ananas",
  "poebanane": "Poe banane",
  "poecitrouille": "Poe citrouille",
  "cheesemangue": "Cheesecake mangue",
  "cheeseframboise": "Cheesecake framboise",
  "gyoza": "Gyoza",
  "gnem": "Grand nem",
  "pnem": "Petit nem",
  "sesame": "Boule de sésame",
  "banhbao": "Banh Bao",
  "chr_pain": "Pain",
  "samossa": "Samossa",
  "brochettes": "Brochettes",
  "chr_farce_wonton": "FARCE wonton",
  "chr_salades": "Salades (pieds)",
  "chr_concombres": "Concombres",
  "chr_carottes": "Carottes",
  "chr_oignons_secs": "Oignons secs",
  "chr_oignons_verts": "Oignons verts",
  "chr_ail": "Ail",
  "chr_vinaigre_blanc": "Vinaigre blanc",
  "chr_nuoc_mam": "Nuoc mam",
  "chr_vetsin": "Vetsin",
  "chr_poivre": "Poivre",
  "chr_maggie": "Maggie",
  "chr_sel": "Sel",
  "chr_citron": "Citron",
  "chr_curry_japonais": "Curry japonais",
  "chr_curry": "Curry",
  "chr_soyou_poisson": "Soyou poisson",
  "chr_soyou_sachet_rouge": "Soyou sachet rouge",
  "chr_soyou_yamasa_bouteilles": "Soyou YAMASA bouteilles",
  "chr_wasabi": "WASABI",
  "chr_gingembre": "GINGEMBRE",
  "chr_navet": "Navet",
  "chr_panko": "Panko",
  "chr_nori": "Nori",
  "chr_sesames_grilles": "Sésames grillés",
  "chr_sauce_cacahuete": "Sauce cacahuète",
  "chr_sauce_huitres": "Sauce huîtres",
  "chr_sauce_bbq": "Sauce BBQ",
  "chr_ketchup": "KETCHUP",
  "chr_sweet_chili": "SWEET CHILI",
  "chr_huile_sesames": "HUILE SÉSAMES",
  "chr_beurre": "Beurre",
  "chr_oeufs": "Oeufs",
  "chr_bull_dog_teriyaki": "Bull dog teriyaki",
  "chr_mirin": "Mirin",
  "chr_bombe_graisse": "BOMBE GRAISSE",
  "chr_ito_sugar_free_600_ml": "Ito sugar free 600 ml",
  "chr_ito_sugar_free_300ml": "Ito sugar free 300ml",
  "chr_ito_lychee": "Ito lychee",
  "chr_ito_peach": "Ito peach",
  "chr_ito_citron": "Ito citron",
  "siumai": "Siu Mai",
  "villerolls": "Rolls (Ville)"
};
